import {
  LevelTwoNodeSize,
  SiteColorNode,
  SiteNodeSize,
  LevelOneNodeSize,
  BioColorNode,
  HealthColorNode,
  MedColorNode,
  PharmaColorNode,
  SiteLinkSize,
  particleCount,
  ParticleSize,
  SiteColorLink,
  LevelOneLinkSize,
  PharmaColorLink,
  BioColorLink,
  LevelTwoLinkSize,
  HealthColorLink,
  MedColorLink,
} from "./config";

export const data = {
  nodes: [
    {
      id: "About",
      link: "about",
      nodeSize: LevelOneNodeSize,
      nodeColor: SiteColorNode,
    },

    {
      id: "Home",
      link: "home",
      nodeSize: SiteNodeSize,
      nodeColor: SiteColorNode,
    },
    {
      id: "Team",
      link: "team",
      nodeSize: LevelOneNodeSize,
      nodeColor: SiteColorNode,
    },
    /* --------------- BioTech --------------- */
    {
      id: "BioTech",
      link: "biotech",
      nodeSize: LevelOneNodeSize,
      nodeColor: BioColorNode,
    },
    {
      id: "BioTech Contact",
      link: "contact",
      nodeSize: LevelTwoNodeSize,
      nodeColor: BioColorNode,
    },
    {
      id: "BioTech PreSeed",
      link: "biotech_preseed",
      nodeSize: LevelTwoNodeSize,
      nodeColor: BioColorNode,
    },
    {
      id: "BioTech Seed",
      link: "biotech_seed",
      nodeSize: LevelTwoNodeSize,
      nodeColor: BioColorNode,
    },
    {
      id: "BioTech Series A",
      link: "biotech_series_a",
      nodeSize: LevelTwoNodeSize,
      nodeColor: BioColorNode,
    },
    {
      id: "BioTech Series B",
      link: "biotech_series_b",
      nodeSize: LevelTwoNodeSize,
      nodeColor: BioColorNode,
    },
    {
      id: "BioTech Mezzanine",
      link: "biotech_mezzanine",
      nodeSize: LevelTwoNodeSize,
      nodeColor: BioColorNode,
    },
    {
      id: "BioTech Public",
      link: "biotech_public",
      nodeSize: LevelTwoNodeSize,
      nodeColor: BioColorNode,
    },
    /* --------------- HealthTech --------------- */
    {
      id: "HealthTech",
      link: "healthtech",
      nodeSize: LevelOneNodeSize,
      nodeColor: HealthColorNode,
    },
    {
      id: "HealthTech Contact",
      link: "contact",
      nodeSize: LevelTwoNodeSize,
      nodeColor: HealthColorNode,
    },
    {
      id: "HealthTech PreSeed",
      link: "healthtech_preseed",
      nodeSize: LevelTwoNodeSize,
      nodeColor: HealthColorNode,
    },
    {
      id: "HealthTech Seed",
      link: "healthtech_seed",
      nodeSize: LevelTwoNodeSize,
      nodeColor: HealthColorNode,
    },
    {
      id: "HealthTech Series A",
      link: "healthtech_series_a",
      nodeSize: LevelTwoNodeSize,
      nodeColor: HealthColorNode,
    },
    {
      id: "HealthTech Series B",
      link: "healthtech_series_b",
      nodeSize: LevelTwoNodeSize,
      nodeColor: HealthColorNode,
    },
    {
      id: "HealthTech Mezzanine",
      link: "healthtech_mezzanine",
      nodeSize: LevelTwoNodeSize,
      nodeColor: HealthColorNode,
    },
    {
      id: "HealthTech Public",
      link: "healthtech_public",
      nodeSize: LevelTwoNodeSize,
      nodeColor: HealthColorNode,
    },
    /* --------------- MedTech --------------- */
    {
      id: "MedTech",
      link: "medtech",
      nodeSize: LevelOneNodeSize,
      nodeColor: MedColorNode,
    },
    {
      id: "MedTech Contact",
      link: "contact",
      nodeSize: LevelTwoNodeSize,
      nodeColor: MedColorNode,
    },
    {
      id: "MedTech PreSeed",
      link: "medtech_preseed",
      nodeSize: LevelTwoNodeSize,
      nodeColor: MedColorNode,
    },
    {
      id: "MedTech Seed",
      link: "medtech_seed",
      nodeSize: LevelTwoNodeSize,
      nodeColor: MedColorNode,
    },
    {
      id: "MedTech Series A",
      link: "medtech_series_a",
      nodeSize: LevelTwoNodeSize,
      nodeColor: MedColorNode,
    },
    {
      id: "MedTech Series B",
      link: "medtech_series_b",
      nodeSize: LevelTwoNodeSize,
      nodeColor: MedColorNode,
    },
    {
      id: "MedTech Mezzanine",
      link: "medtech_mezzanine",
      nodeSize: LevelTwoNodeSize,
      nodeColor: MedColorNode,
    },
    {
      id: "MedTech Public",
      link: "medtech_public",
      nodeSize: LevelTwoNodeSize,
      nodeColor: MedColorNode,
    },
    /* --------------- PharmaTech --------------- */
    {
      id: "PharmaTech",
      link: "pharmatech",
      nodeSize: LevelOneNodeSize,
      nodeColor: PharmaColorNode,
    },
    {
      id: "PharmaTech Contact",
      link: "contact",
      nodeSize: LevelTwoNodeSize,
      nodeColor: PharmaColorNode,
    },
    {
      id: "PharmaTech PreSeed",
      link: "pharmatech_preseed",
      nodeSize: LevelTwoNodeSize,
      nodeColor: PharmaColorNode,
    },
    {
      id: "PharmaTech Seed",
      link: "pharmatech_seed",
      nodeSize: LevelTwoNodeSize,
      nodeColor: PharmaColorNode,
    },
    {
      id: "PharmaTech Series A",
      link: "pharmatech_series_a",
      nodeSize: LevelTwoNodeSize,
      nodeColor: PharmaColorNode,
    },
    {
      id: "PharmaTech Series B",
      link: "pharmatech_series_b",
      nodeSize: LevelTwoNodeSize,
      nodeColor: PharmaColorNode,
    },
    {
      id: "PharmaTech Mezzanine",
      link: "pharmatech_mezzanine",
      nodeSize: LevelTwoNodeSize,
      nodeColor: PharmaColorNode,
    },
    {
      id: "PharmaTech Public",
      link: "pharmatech_public",
      nodeSize: LevelTwoNodeSize,
      nodeColor: PharmaColorNode,
    },
  ],

  /* --------------- Links --------------- */

  links: [
    {
      source: "Home",
      target: "About",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: SiteLinkSize,
      linkColor: SiteColorLink,
    },
    {
      source: "Home",
      target: "Team",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: SiteLinkSize,
      linkColor: SiteColorLink,
    },

    /* --------------- BioTech --------------- */
    {
      source: "BioTech",
      target: "Home",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelOneLinkSize,
      linkColor: BioColorLink,
    },
    {
      source: "BioTech Contact",
      target: "BioTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelOneLinkSize,
      linkColor: BioColorLink,
    },
    {
      source: "BioTech PreSeed",
      target: "BioTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: BioColorLink,
    },
    {
      source: "BioTech Seed",
      target: "BioTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: BioColorLink,
    },
    {
      source: "BioTech Series A",
      target: "BioTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: BioColorLink,
    },
    {
      source: "BioTech Series B",
      target: "BioTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: BioColorLink,
    },
    {
      source: "BioTech Mezzanine",
      target: "BioTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: BioColorLink,
    },
    {
      source: "BioTech Public",
      target: "BioTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: BioColorLink,
    },
    /* --------------- HealthTech --------------- */
    {
      source: "HealthTech",
      target: "Home",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelOneLinkSize,
      linkColor: HealthColorLink,
    },
    {
      source: "HealthTech Contact",
      target: "HealthTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelOneLinkSize,
      linkColor: HealthColorLink,
    },
    {
      source: "HealthTech PreSeed",
      target: "HealthTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: HealthColorLink,
    },
    {
      source: "HealthTech Seed",
      target: "HealthTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: HealthColorLink,
    },
    {
      source: "HealthTech Series A",
      target: "HealthTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: HealthColorLink,
    },
    {
      source: "HealthTech Series B",
      target: "HealthTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: HealthColorLink,
    },
    {
      source: "HealthTech Mezzanine",
      target: "HealthTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: HealthColorLink,
    },
    {
      source: "HealthTech Public",
      target: "HealthTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: HealthColorLink,
    },
    /* --------------- MedTech --------------- */
    {
      source: "MedTech",
      target: "Home",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelOneLinkSize,
      linkColor: MedColorLink,
    },
    {
      source: "MedTech Contact",
      target: "MedTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelOneLinkSize,
      linkColor: MedColorLink,
    },
    {
      source: "MedTech PreSeed",
      target: "MedTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: MedColorLink,
    },
    {
      source: "MedTech Seed",
      target: "MedTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: MedColorLink,
    },
    {
      source: "MedTech Series A",
      target: "MedTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: MedColorLink,
    },
    {
      source: "MedTech Series B",
      target: "MedTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: MedColorLink,
    },
    {
      source: "MedTech Mezzanine",
      target: "MedTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: MedColorLink,
    },
    {
      source: "MedTech Public",
      target: "MedTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: MedColorLink,
    },
    /* --------------- PharmaTech --------------- */
    {
      source: "PharmaTech",
      target: "Home",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelOneLinkSize,
      linkColor: PharmaColorLink,
    },
    {
      source: "PharmaTech Contact",
      target: "PharmaTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelOneLinkSize,
      linkColor: PharmaColorLink,
    },
    {
      source: "PharmaTech PreSeed",
      target: "PharmaTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelOneLinkSize,
      linkColor: PharmaColorLink,
    },
    {
      source: "PharmaTech Seed",
      target: "PharmaTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: PharmaColorLink,
    },
    {
      source: "PharmaTech Series A",
      target: "PharmaTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: PharmaColorLink,
    },
    {
      source: "PharmaTech Series B",
      target: "PharmaTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: PharmaColorLink,
    },
    {
      source: "PharmaTech Mezzanine",
      target: "PharmaTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: PharmaColorLink,
    },
    {
      source: "PharmaTech Public",
      target: "PharmaTech",
      particleCount: particleCount,
      particleSize: ParticleSize,
      linkSize: LevelTwoLinkSize,
      linkColor: PharmaColorLink,
    },
  ],
};
