// ARTICLES

export const ARTICLE_IMAGE_SIZE_DESKTOP = 400;
export const ARTICLE_IMAGE_SIZE_MOBILE = 180;

export const BANNER_PADDING_TOP_DESKTOP = 210;
export const BANNER_PADDING_TOP_MOBILE = 190;

// CARDS
export const CARD_ROW_HEIGHT_DESKTOP = 200;
export const CARD_ROW_HEIGHT_MOBILE = 140;

export const CARD_HEIGHT_DESKTOP = CARD_ROW_HEIGHT_DESKTOP;
export const CARD_WIDTH_DESKTOP = 280;

export const CARD_HEIGHT_MOBILE = CARD_ROW_HEIGHT_MOBILE;
export const CARD_WIDTH_MOBILE = 240;

export const CARD_TEXT_COLOR = "hsl(0, 0%, 90%)";
export const CARD_TEXT_COLOR_HOVER = "hsl(0, 86%, 46%)";
export const CARD_BACKGROUND_COLOR = "rgba(0, 0, 0, 0.4)";
export const CARD_BACKGROUND_COLOR_HOVER = "rgba(50, 50, 50, 0.4)";
