export const dataMarkets = [
  {
    id: 1,
    label: "HEALTHTECH",
    height: 20,
    value: "$400B",
    color: "#ffffff",
    backgroundColor: "#5e4150",
    text: "Eleven supports Healthtech ventures from early private stages through initial public offering (IPO), and assists public companies to identify innovative private sector partners.",
  },
  {
    id: 2,
    label: "MEDTECH",
    height: 30,
    value: "$500B",
    color: "#ffffff",
    backgroundColor: "#834747",
    text: "Eleven supports Medtech ventures from early private stages through initial public offering (IPO), and assists public companies to identify innovative private sector partners.",
  },
  {
    id: 3,
    label: "BIOTECH",
    height: 50,
    value: "$700B",
    color: "#ffffff",
    backgroundColor: "#78633e",
    text: "Eleven supports Biotech ventures from early private stages through initial public offering (IPO), and assists public companies to identify innovative private sector partners.",
  },
  {
    id: 4,
    label: "PHARMATECH",
    height: 100,
    value: "$1.2T",
    color: "#ffffff",
    backgroundColor: "#76764f",
    text: "Eleven supports Pharmatech ventures from early private stages through initial public offering (IPO), and assists public companies to identify innovative private sector partners.",
  },
];
