export const dataAdvisors = [
  // {
  //   id: 1,
  //   order: 4,
  //   nameLast: "Dunning",
  //   nameFirst: "Todd",
  //   role: "Advisor",
  //   desc: "Description here. Description here. Description here. Description here.  Description here. Description here.",
  //   photo: "dunning.jpeg",
  // },
  {
    id: 2,
    order: 2,
    nameLast: "Fine",
    nameFirst: "Benjamin",
    role: "Advisor",
    desc: "Description here. Description here. Description here. Description here.  Description here. Description here.",
    photo: "fine.jpeg",
  },
  {
    id: 3,
    order: 1,
    nameLast: "Kleck",
    nameFirst: "Jeff",
    role: "Advisor",
    desc: "Description here. Description here. Description here. Description here.  Description here. Description here.",
    photo: "kleck.jpeg",
  },
  {
    id: 4,
    order: 3,
    nameLast: "Lungren",
    nameFirst: "Matthew",
    role: "Advisor",
    desc: "Matt Bio",
    photo: "lungren.jpeg",
  },
];
