import { HEADER_HEIGHT, HEADER_MOBILE_HEIGHT } from "./Layout";

// Banner
export const BANNER_HEIGHT_DESKTOP = 440;
export const BANNER_HEIGHT_MOBILE = 380;
export const BANNER_PADDING_TOP_DESKTOP = HEADER_HEIGHT + 60;
export const BANNER_PADDING_TOP_MOBILE = HEADER_MOBILE_HEIGHT + 40;

