import { HEADER_HEIGHT_DESKTOP, HEADER_HEIGHT_MOBILE } from "./Layout";

// Banner
export const BANNER_HEIGHT_DESKTOP = 440;
export const BANNER_HEIGHT_MOBILE = 380;
export const BANNER_PADDING_TOP_DESKTOP = HEADER_HEIGHT_DESKTOP + 120;
export const BANNER_PADDING_TOP_MOBILE = HEADER_HEIGHT_MOBILE + 60;
