import { HEADER_HEIGHT, HEADER_MOBILE_HEIGHT } from "./Layout";

// Banner
export const BANNER_HEIGHT_DESKTOP = 400;
export const BANNER_HEIGHT_MOBILE = 340;
export const BANNER_PADDING_TOP_DESKTOP = HEADER_HEIGHT + 60;
export const BANNER_PADDING_TOP_MOBILE = HEADER_MOBILE_HEIGHT + 40;
export const BANNER_CONTENT_HEIGHT_DESKTOP =
  (BANNER_HEIGHT_DESKTOP - BANNER_PADDING_TOP_DESKTOP) * 0.9;
export const BANNER_CONTENT_HEIGHT_MOBILE =
  (BANNER_HEIGHT_MOBILE - BANNER_PADDING_TOP_MOBILE) * 0.9;
