import {
  BANNER_CONTENT_HEIGHT_DESKTOP,
  BANNER_CONTENT_HEIGHT_MOBILE,
} from "./Layout";

// Charts
export const CHART_LABEL_DESKTOP = "1.2em";
export const CHART_LABEL_MOBILE = "1em";
export const COLUMN_GRID_GAP_DESKTOP = "10px";
export const COLUMN_GRID_GAP_MOBILE = "7px";

/* Chart Height */
export const CHART_SECTION_HEIGHT_DESKTOP = BANNER_CONTENT_HEIGHT_DESKTOP * 0.5;
export const CHART_SECTION_HEIGHT_MOBILE = BANNER_CONTENT_HEIGHT_MOBILE * 0.5;

/* Chart Legend Height */
export const CHART_LEGEND_HEIGHT_DESKTOP = 20;
export const CHART_LEGEND_HEIGHT_MOBILE = 10;

/* Series Height */
export const CHART_HEIGHT_DESKTOP =
  CHART_SECTION_HEIGHT_DESKTOP - CHART_LEGEND_HEIGHT_DESKTOP;
export const CHART_HEIGHT_MOBILE =
  CHART_SECTION_HEIGHT_MOBILE - CHART_LEGEND_HEIGHT_MOBILE;

/* Spacer Height */
export const CHART_SPACER_HEIGHT_DESKTOP = BANNER_CONTENT_HEIGHT_DESKTOP * 0.07;
export const CHART_SPACER_HEIGHT_MOBILE = BANNER_CONTENT_HEIGHT_MOBILE * 0.02;

/* Text Height */
export const CHART_TEXT_HEIGHT_DESKTOP =
  BANNER_CONTENT_HEIGHT_DESKTOP -
  (CHART_SECTION_HEIGHT_DESKTOP + CHART_SPACER_HEIGHT_DESKTOP);
export const CHART_TEXT_HEIGHT_MOBILE =
  BANNER_CONTENT_HEIGHT_MOBILE -
  (CHART_SECTION_HEIGHT_MOBILE + CHART_SPACER_HEIGHT_MOBILE);
  
// Transitions
export const CHART_COLUMN_TRANSITION = 400;
export const CHART_COLUMN_STAGGER = 200;
export const CHART_TEXT_TRANSITION = 600;
