export const dataPracticeAreas = [
  {
    id: 0,
    title: "Clinical",
    text: "The world's foremost clinical talent guides Eleven's digital health ventures to the best possible outcomes. Deep technical and clinical support for broader consumer health sector landscape (e.g., patient engagement, wearables, digital health and wellness).",
    color: "#FFFFFF",
    backgroundColor: "#858457",
    buttonText: "Case Studies",
    buttonTo: "/casestudies",
    buttonColor: "gray",
  },
  {
    id: 1,
    title: "AI/ML",
    text: "Experts from the preeminent academic and commercial AI/ML programs accelerate Eleven's digital health ventures.",
    color: "#FFFFFF",
    backgroundColor: "#6d825c",
    buttonText: "Case Studies",
    buttonTo: "/casestudies",
    buttonColor: "gray",
  },
  {
    id: 2,
    title: "Product",
    text: "Commercial product specialists from leading commercial enterprises help sculpt Eleven's digital health ventures.  Go-to-market, product positioning, price point for clinical machine learning and digital health solutions. Segment landscape, needs, and priorities to drive adoption.  ",
    color: "#FFFFFF",
    backgroundColor: "#557f66",
    buttonText: "Case Studies",
    buttonTo: "/casestudies",
    buttonColor: "gray",
  },
  {
    id: 4,
    title: "Marketing",
    text: "Professionals shaping some of the most storied companies in modern healthcare position Eleven's digital health ventures.  Support for early adoption academic initiatives and activities including grants, publications, and collaborations.",
    color: "#FFFFFF",
    backgroundColor: "#45737e",
    buttonText: "Case Studies",
    buttonTo: "/casestudies",
    buttonColor: "gray",
  },
  {
    id: 5,
    title: "Regulatory",
    color: "#FFFFFF",
    text: "Authorities in FDA regulation and practice provide support for Eleven's digital health ventures.",
    backgroundColor: "#416283",
    buttonText: "Case Studies",
    buttonTo: "/casestudies",
    buttonColor: "gray",
  },
  {
    id: 6,
    title: "Strategy",
    color: "#FFFFFF",
    text: "Strategists responsible for inventing new healthcare categories over the two decades fabricate direction for Eleven's digital health ventures. Strategic investments and structuring corporate vehicles (e.g., corporate venture capital, or CVC).  Growth guidance including market segment, therapeutic area or disease category from competitive, partnering or investment perspectives.  Multidisciplinary fundraising, positioning vision, strategy and business model for digital health and digital medicine.  M & A commercial due diligence including market assessment, evaluation of the competitive landscape, and analysis of the target's value proposition and post-acquisition growth strategy.",
    backgroundColor: "#37486e",
    buttonText: "Case Studies",
    buttonTo: "/casestudies",
    buttonColor: "gray",
  },
];
