export const dataPracticeAreas = [
  {
    id: 0,
    title: "Clinical",
    text: "Eleven accesses the foremost clinical talent in the world to accelerate digital health ventures.",
    color: "#FFFFFF",
    backgroundColor: "#858457",
    buttonText: "Case Studies",
    buttonTo: "/casestudies",
    buttonColor: "gray",
  },
  {
    id: 1,
    title: "AI/ML",
    text: "Eleven accesses the foremost AI/ML talent in the world to accelerate digital health ventures.",
    color: "#FFFFFF",
    backgroundColor: "#6d825c",
    buttonText: "Case Studies",
    buttonTo: "/casestudies",
    buttonColor: "gray",
  },
  {
    id: 2,
    title: "Product",
    text: "Eleven includes the foremost product talent in the world to accelerate digital health ventures.",
    color: "#FFFFFF",
    backgroundColor: "#557f66",
    buttonText: "Case Studies",
    buttonTo: "/casestudies",
    buttonColor: "gray",
  },
  {
    id: 4,
    title: "Marketing",
    text: "Eleven accesses the foremost digital health marketing talent in the world to advance ventures.",
    color: "#FFFFFF",
    backgroundColor: "#45737e",
    buttonText: "Case Studies",
    buttonTo: "/casestudies",
    buttonColor: "gray",
  },
  {
    id: 5,
    title: "Regulatory",
    color: "#FFFFFF",
    text: "Eleven uses highly market experienced experts to determine where to focus regulatory support for digital health ventures.",
    backgroundColor: "#416283",
    buttonText: "Case Studies",
    buttonTo: "/casestudies",
    buttonColor: "gray",
  },
  {
    id: 6,
    title: "Strategy",
    color: "#FFFFFF",
    text: "Eleven includes some of the world’s most successful digital health enterprisers in support of venture strategy.",
    backgroundColor: "#37486e",
    buttonText: "Case Studies",
    buttonTo: "/casestudies",
    buttonColor: "gray",
  },
];
