export const dataHome = [
  {
    id: 1,
    order: 1,
    title: "Engaging with Eleven",
    text: "<b>(How we work with your startup or portfolio companies)</b>",
    side: "left",
    backgroundColor: 1,
    buttonText: "Engagement",
    buttonTo: "/engagement",
  },
  {
    id: 2,
    order: 2,
    title: "Our process",
    text: "(Describe our process workflow and milestones, deliverables and success measurement)",
    side: "right",
    backgroundColor: 2,
    buttonText: "Process",
    buttonTo: "/process",
  },
  {
    id: 3,
    order: 3,
    title: "Fitting in to your venture's stage",
    text: "(Show where our services fit in to your venture timeline)",
    side: "right",
    backgroundColor: 3,
    buttonText: "venture Stages",
    buttonTo: "/venturestage",
  },
];
