export const dataOrgs = [
  {
    id: 1,
    order: 1,
    title: "University of Toronto",
    image: "uot.png",
    width: 150,
  },
  {
    id: 2,
    order: 2,
    title: "UCSF",
    image: "ucsf.png",
    width: 80,
  },
  {
    id: 3,
    order: 3,
    title: "Stanford University",
    image: "stanford.png",
    width: 140,
  },
  {
    id: 4,
    order: 4,
    title: "MIT",
    image: "mit.png",
    width: 150,
  },
  {
    id: 5,
    order: 5,
    title: "Harvard University",
    image: "harvard.png",
    width: 150,
  },
  {
    id: 6,
    order: 6,
    title: "Duke University",
    image: "duke.png",
    width: 100,
  },
  {
    id: 7,
    order: 8,
    title: "Microsoft",
    image: "microsoft.png",
    width: 150,
  },
  {
    id: 8,
    order: 8,
    title: "Google",
    image: "google.png",
    width: 120,
  },
  {
    id: 9,
    order: 9,
    title: "Amazon Web Services",
    image: "aws.png",
    width: 80,
  },
];
