export const dataService = [
  {
    id: 1,
    order: 1,
    title: "Product/Market fit",
    text: "Eleven understands your healthcare customer - from payers to providers to insurers, from academia to clinical practice, across bio to med to health to pharma. We'll enable you with:<ul><li>Segment landscape, needs, and priorities to drive adoption.</li> <li> Go-to-market, product positioning, price point for clinical machine learning and digital health solutions. </li><li>Support for early adoption academic initiatives and activities including grants, publications, and collaborations.</li><li>Deep technical and clinical support for broader consumer health sector landscape (e.g., patient engagement, wearables, digital health and wellness).</li></ul>",
    side: "left",
    backgroundColor: 1,
    buttonText:"",
    buttonTo:""
  },
  {
    id: 2,
    order: 2,
    title: "Growth and Acquisitions",
    text: "From Seed to IPO Eleven shepherds your <b>portfolio companies</b> through the challenging health vertical.<ul><li>Strategic investments and structuring corporate vehicles (e.g., corporate venture capital, or CVC).</li><li>Growth guidance including market segment, therapeutic area or disease category from competitive, partnering or investment perspectives.</li>  <li>Multidisciplinary fundraising,positioning vision, strategy and business model for digital health and digital medicine.</li><li>M &amp; A commercial due diligence including market assessment, evaluation of the competitive landscape, and analysis of the target's value proposition and post-acquisition growth strategy.</li></ul>",
    side: "right",
    backgroundColor: 2,
    buttonText:"Markets",
    buttonTo:"/markets"
  },
  {
    id: 3,
    order: 1,
    title: "Product/Market fit",
    text: "Segment landscape, needs, and priorities to drive adoption",
    side: "left",
    backgroundColor: 1,
  },
  {
    id: 4,
    order: 2,
    title: "Product/Market fit",
    text: "Go-to-market, product positioning, price point for clinical machine learning and digital health solutions.",
    side: "right",
    backgroundColor: 2,
  },
  {
    id: 5,
    order: 3,
    title: "Product/Market fit",
    text: "Support for early adoption academic initiatives and activities including grants, publications, and collaborations.",
    side: "left",
    backgroundColor: 3,
  },
  {
    id: 5,
    order: 4,
    title: "Product/Market fit",
    text: "Deep technical and clinical support for broader consumer health sector landscape (e.g., patient engagement, wearables, digital health and wellness)",
    side: "right",
    backgroundColor: 4,
  },
  {
    id: 7,
    order: 5,
    title: "Growth and Acquisitions",
    text: "Strategic investments and structuring corporate vehicles (e.g., corporate venture capital, or CVC).",
    side: "left",
    backgroundColor: 5,
  },
  {
    id: 8,
    order: 6,
    title: "Growth and Acquisitions",
    text: "Growth guidance including market segment, therapeutic area or disease category from competitive, partnering or investment perspectives.",
    side: "right",
    backgroundColor: 6,
  },
  {
    id: 9,
    order: 7,
    title: "Growth and Acquisitions",
    text: "Multidisciplinary fundraising, positioning vision, strategy and business model for digital health and digital medicine.",
    side: "left",
    backgroundColor: 1,
  },
  {
    id: 10,
    order: 8,
    title: "Growth and Acquisitions",
    text: "M & A commercial due diligence including market assessment, evaluation of the competitive landscape, and analysis of the target's value proposition and post-acquisition growth strategy.",
    side: "right",
    backgroundColor: 2,
  },
];
