export const dataCaseStudies = [
  {
    id: 1,
    title: "1. Product-market fit",
    text: "<p>Technical founders develop novel clinical AI application but struggle to find product market fit.</p><p>Elevens provided a fractional CXAIO that:</p><ul><li>Connected to key opinion leaders at 10 United States hospital systems</li><li>Led product discovery cycles with payors, providers to define ideal customer profile</li><li>Helped develop MVP concept</li><li>Mapped out data integrations with health information systems</li><li>Designed scientific evaluation metrics and communication strategy</li><li>Tested marketing materials for first market segment first early adopters </li><li>Defined pricing model for value based and FFS providers</li><li>Made qualified introductions to help land first paid customer</li></ul>",
    backgroundColor: 1,
    randomHeight: false,
    practiceArea: [
      {
        id: 0,
        label: "Clinical",
        height: 20,
        randomHeight: false,
        backgroundColor: "#858457",
      },
      {
        id: 1,
        label: "AI/ML",
        height: 50,
        randomHeight: false,
        backgroundColor: "#6d825c",
      },
      {
        id: 2,
        label: "Product",
        height: 80,
        randomHeight: false,
        backgroundColor: "#557f66",
      },
      {
        id: 4,
        label: "Marketing",
        height: 40,
        randomHeight: false,
        backgroundColor: "#45737e",
      },
      {
        id: 5,
        label: "Regulatory",
        height: 20,
        randomHeight: false,
        backgroundColor: "#416283",
      },
      {
        id: 6,
        label: "Strategy",
        height: 90,
        randomHeight: false,
        backgroundColor: "#37486e",
      },
    ],
  },
  {
    id: 2,
    title: "2. Early stage, go-to-market plan",
    text: "<p>Pre-seed studio / hospital spin out company with early novel AI model and technical lead but struggling to define go to market plan.</p><p>Elevens provided a fractional CXAIO that:</p><ul><li>Led product management discovery and MVP design, transitioning to full time PM hire</li><li>Validated business model with payors and reimbursement consultant</li><li>Developed data science and engineering team recruiting roadmaps</li><li>Provided real world evaluation framework / measures for presenting results to clinicians / administrators</li><li>Connected company to digital health investors</li><li>Developed health information system integration plan for full cycle MLOps</li><li>Recruited top trained data science lead</li><li>Contacted world leading AI regulatory consultant</li></ul>",
    backgroundColor: 2,
    randomHeight: false,
    practiceArea: [
      {
        id: 0,
        label: "Clinical",
        height: 80,
        randomHeight: false,
        backgroundColor: "#858457",
      },
      {
        id: 1,
        label: "AI/ML",
        height: 80,
        randomHeight: false,
        backgroundColor: "#6d825c",
      },
      {
        id: 2,
        label: "Product",
        height: 80,
        randomHeight: false,
        backgroundColor: "#557f66",
      },
      {
        id: 4,
        label: "Marketing",
        height: 20,
        randomHeight: false,
        backgroundColor: "#45737e",
      },
      {
        id: 5,
        label: "Regulatory",
        height: 20,
        randomHeight: false,
        backgroundColor: "#416283",
      },
      {
        id: 6,
        label: "Strategy",
        height: 90,
        randomHeight: false,
        backgroundColor: "#37486e",
      },
    ],
  },
  {
    id: 3,
    title: "3. Strategic options",
    text: "<p>Point solution AI startup with market traction at growth inflection point exploring next venture financing round or strategic acquisition</p><p>Elevens provided a fractional CXAIO that:</p><ul><li>Leverage expert AI market network to determine company position in market</li><li>Use data and relationships with venture and strategic acquirers to generate real world options for strategic fit</li><li>Create double consent ''good fit'' meeting opportunities between venture and aligned / interested investors</li><li>Recruited top AI executive and board member to prepare for next round</li><li>Provided market perspective and experience to guide CEO / board through diligence and closing process</li></ul>",
    backgroundColor: 3,
    randomHeight: false,
    practiceArea: [
      {
        id: 0,
        label: "Clinical",
        height: 60,
        randomHeight: false,
        backgroundColor: "#858457",
      },
      {
        id: 1,
        label: "AI/ML",
        height: 80,
        randomHeight: false,
        backgroundColor: "#6d825c",
      },
      {
        id: 2,
        label: "Product",
        height: 20,
        randomHeight: false,
        backgroundColor: "#557f66",
      },
      {
        id: 4,
        label: "Marketing",
        height: 20,
        randomHeight: false,
        backgroundColor: "#45737e",
      },
      {
        id: 5,
        label: "Regulatory",
        height: 20,
        randomHeight: false,
        backgroundColor: "#416283",
      },
      {
        id: 6,
        label: "Strategy",
        height: 90,
        randomHeight: false,
        backgroundColor: "#37486e",
      },
    ],
    buttonText: "Markets",
    buttonTo: "/markets",
    buttonColor: "",
  },
];
