// Footer
export const FOOTER_HEIGHT_DESKTOP = 400;
export const FOOTER_CONTAINER_HEIGHT_DESKTOP = FOOTER_HEIGHT_DESKTOP * 0.8;
export const FOOTER_CONTENT_HEIGHT_DESKTOP = FOOTER_CONTAINER_HEIGHT_DESKTOP * 0.8;
export const FOOTER_COPYRIGHT_HEIGHT_DESKTOP = FOOTER_CONTAINER_HEIGHT_DESKTOP * 0.2;

export const FOOTER_HEIGHT_MOBILE = 350;
export const FOOTER_CONTAINER_HEIGHT_MOBILE = FOOTER_HEIGHT_MOBILE * 0.8;
export const FOOTER_LOGO_HEIGHT_MOBILE = FOOTER_CONTAINER_HEIGHT_MOBILE * 0.15;
export const FOOTER_CONTENT_HEIGHT_MOBILE = FOOTER_CONTAINER_HEIGHT_MOBILE * 0.5;
export const FOOTER_COPYRIGHT_HEIGHT_MOBILE = FOOTER_CONTAINER_HEIGHT_MOBILE * 0.2;